<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema"
				  targetNamespace="http://sundhedsdatastyrelsen.dk/personid/2020/01/01">
    <wsdl:types>

        <!-- Just to keep track of all sub xsd's, contains no actual services -->

		<xs:schema targetNamespace="http://sundhedsdatastyrelsen.dk/personid/2020/01/01"
                   elementFormDefault="qualified">
            <xs:include schemaLocation="../schemas/2020/01/01/PersonIdentifierModification.xsd"/>
            <xs:include schemaLocation="../schemas/2020/01/01/PersonIdentifierModificationAction.xsd"/>
        </xs:schema>

    </wsdl:types>

</wsdl:definitions>
