<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema"
                  xmlns:medicinecard2013pem="http://www.dkma.dk/medicinecard/xml.schema/2013/pem"
                  xmlns:tns="http://www.dkma.dk/medicinecard/xml.schema/2013/pem"
                  xmlns:medcom="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd"
                  targetNamespace="http://www.dkma.dk/medicinecard/xml.schema/2013/pem">

    <wsdl:types>

        <xs:schema targetNamespace="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd">
            <xs:include schemaLocation="../schemas/2008/06/01/medcom.xsd"/>
        </xs:schema>

        <xs:schema targetNamespace="http://www.dkma.dk/medicinecard/xml.schema/2013/pem" elementFormDefault="qualified">

			<xs:include schemaLocation="../schemas/2013/pem/OrderEffectuationRequest.xsd"/>
			<xs:include schemaLocation="../schemas/2013/pem/OrderEffectuationResponse.xsd"/>

        </xs:schema>

    </wsdl:types>


    <wsdl:message name="OrderEffectuationRequest_2013_pem">
        <wsdl:part name="OrderEffectuationRequest" element="medicinecard2013pem:OrderEffectuationRequest"/>
    </wsdl:message>
    <wsdl:message name="OrderEffectuationResponse_2013_pem">
        <wsdl:part name="OrderEffectuationResponse" element="medicinecard2013pem:OrderEffectuationResponse"/>
    </wsdl:message>
    
    <wsdl:message name="DGWSFault">
        <wsdl:part name="fault" element="medcom:FaultCode"/>
    </wsdl:message>


    <wsdl:portType name="EffectuationOrderingPEMPortType">

        <wsdl:operation name="OrderEffectuation_2013_pem">
            <wsdl:input name="OrderEffectuationRequest_2013_pem" message="tns:OrderEffectuationRequest_2013_pem"/>
            <wsdl:output name="OrderEffectuationResponse_2013_pem" message="tns:OrderEffectuationResponse_2013_pem"/>
            <wsdl:fault name="DGWSFault" message="tns:DGWSFault"/>
        </wsdl:operation>
        
    </wsdl:portType>

    <wsdl:binding name="EffectuationOrderingPEMBinding" type="tns:EffectuationOrderingPEMPortType">

        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="OrderEffectuation_2013_pem">
            <soap:operation soapAction="http://www.dkma.dk/medicinecard/xml.schema/2013/pem#OrderEffectuation" style="document"/>
            <wsdl:input name="OrderEffectuationRequest_2013_pem">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="OrderEffectuationResponse_2013_pem">
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="DGWSFault">
                <soap:fault name="DGWSFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
        
    </wsdl:binding>

    <wsdl:service name="EffectuationOrderingPEM">
        <wsdl:port name="EffectuationOrderingPEMPort" binding="tns:EffectuationOrderingPEMBinding">
            <soap:address location="http://trifork.lms.trifork.com/fmk12/ws/EffectuationOrderingPEM"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
