<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		xmlns:mc160="http://fmk-teknik.dk/160/advis"
		targetNamespace="http://fmk-teknik.dk/160/advis"
		elementFormDefault="qualified">

	<include schemaLocation="../common/PersonIdentifier.xsd"/>
	<include schemaLocation="DispensingCardIdentifier.xsd"/>
	<include schemaLocation="DispensingPeriodInformation.xsd"/>

	<complexType name="DispensingCardModificationIdentifiersType">
		<annotation>
			<documentation xml:lang="en-GB">Identifiers for a dispensing card modification</documentation>
			<documentation xml:lang="da-DK">Identifikatorer for en ændring af et dispenseringskort</documentation>
		</annotation>
		<sequence>
			<element name="PersonIdentifier" type="mc160:PersonIdentifierType"/>
			<element name="Identifier" type="mc160:DispensingCardIdentifierType"/>
			<element name="DispensingPeriod" type="mc160:DispensingPeriodInformationType" minOccurs="0"/>
		</sequence>
	</complexType>
</schema>
