<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		xmlns:mc160="http://fmk-teknik.dk/160"
		targetNamespace="http://fmk-teknik.dk/160"
		elementFormDefault="qualified" attributeFormDefault="unqualified">

	<include schemaLocation="DrugMedicationIdentifier.xsd"/>
	<include schemaLocation="DrugMedicationVersion.xsd"/>

	<element name="DrugMedicationWithNegativeConsent" type="mc160:DrugMedicationWithNegativeConsentType">
		<annotation>
			<documentation xml:lang="en-GB">This structure contains drug medication identifier and version for a drug medication with negative consent.</documentation>
			<documentation xml:lang="da-DK">Denne struktur indeholder id og version for en lægemiddelordination med negativt samtykke.</documentation>
		</annotation>
	</element>

	<complexType name="DrugMedicationWithNegativeConsentType">
		<sequence>
			<element name="Identifier" type="mc160:DrugMedicationIdentifierType"/>
			<element name="Version" type="mc160:DrugMedicationVersionType"/>
		</sequence>
	</complexType>
</schema>
