<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		xmlns:mc160="http://fmk-teknik.dk/160"
		targetNamespace="http://fmk-teknik.dk/160"
		elementFormDefault="qualified" attributeFormDefault="unqualified">

	<include schemaLocation="HasNegativeConsent.xsd"/>
	<include schemaLocation="PersonIdentifier.xsd"/>
	<include schemaLocation="DrugMedicationsWithNegativeConsent.xsd"/>

	<element name="HiddenData" type="mc160:HiddenDataType">
		<annotation>
			<documentation xml:lang="en-GB">Specification of the reason, in case of hidden data, together with a list of hidden elements</documentation>
			<documentation xml:lang="da-DK">Angiver årsagen til evt. skjulte data samt liste med skjulte elementer</documentation>
		</annotation>
	</element>

	<complexType name="HiddenDataType">
		<sequence>
			<element name="PersonIdentifier" type="mc160:PersonIdentifierType"/>
			<element name="HasNegativeConsent" type="mc160:HasNegativeConsentType" />
			<element name="ElementsWithNegativeConsentList" type="mc160:ElementsWithNegativeConsentListType">
				<annotation>
					<documentation xml:lang="en-GB">Elements that were omitted from the response because of negative consent</documentation>
					<documentation xml:lang="da-DK">Elementer, der er udeladt af svaret på grund af negativt samtykke</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
</schema>
