<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:mc160="http://fmk-teknik.dk/160"
        targetNamespace="http://fmk-teknik.dk/160"
        elementFormDefault="qualified" attributeFormDefault="unqualified">

    <annotation>
        <documentation xml:lang="en-GB">Technical session id defined by the client system that  links more registrations belonging to the same session</documentation>
        <documentation xml:lang="da-DK">Teknisk sessions id defineret af klient systemerne der derved kan koble flere kald hørende til den samme konsultation</documentation>
    </annotation>

    <element name="MinLogSessionId" type="mc160:MinLogSessionIdType">
        <annotation>
            <documentation xml:lang="en-GB">Free-standing SOAP header carrying the technical session id defined by the client system</documentation>
            <documentation xml:lang="da-DK">Fritstående SOAP header med det tekniske sessions id defineret af klient systemerne</documentation>
        </annotation>
    </element>

    <simpleType name="MinLogSessionIdType">
        <restriction base="string">
            <maxLength value="40"/>
        </restriction>
    </simpleType>
</schema>