<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		xmlns:mc160="http://fmk-teknik.dk/160"
		targetNamespace="http://fmk-teknik.dk/160"
		elementFormDefault="qualified" attributeFormDefault="unqualified">
	
	<include schemaLocation="PersonName.xsd"/>
	<include schemaLocation="BirthDate.xsd"/>
	<include schemaLocation="Gender.xsd"/>
	
	<element name="Person" type="mc160:PersonType"/>
	<complexType name="PersonType">
		<annotation>
			<documentation xml:lang="en-GB">Information about a person</documentation>
			<documentation xml:lang="da-DK">Oplysninger om en person</documentation>
		</annotation>
		<sequence>
			<element name="Name" type="mc160:PersonNameType"/>
			<element name="BirthDate" type="mc160:BirthDateType"/>
			<element name="Gender" type="mc160:GenderType"/>
		</sequence>
	</complexType>
</schema>
