<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		xmlns:mc160="http://fmk-teknik.dk/160/advis"
		targetNamespace="http://fmk-teknik.dk/160/advis"
		elementFormDefault="qualified">

	<include schemaLocation="../common/PersonIdentifier.xsd"/>
	<include schemaLocation="RequestForWarrantModificationAction.xsd"/>
	<include schemaLocation="RequestForWarrantModificationIdentifiers.xsd"/>

	<element name="RequestForWarrantModification" type="mc160:RequestForWarrantModificationType"/>

	<complexType name="RequestForWarrantModificationType">
		<annotation>
			<documentation xml:lang="en-GB">Information about a request-for-warrant modification</documentation>
			<documentation xml:lang="da-DK">Information om en ændring af en anmodning om et udleveringsgrundlag</documentation>
		</annotation>
		<sequence>
			<element name="Action" type="mc160:RequestForWarrantModificationActionType"/>
			<element name="PersonIdentifier" type="mc160:PersonIdentifierType"/>
			<element name="RequestForWarrant" type="mc160:RequestForWarrantModificationIdentifiersType"/>
			<any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
		</sequence>
	</complexType>
</schema>
