<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		xmlns:mc160="http://fmk-teknik.dk/160/advis"
		targetNamespace="http://fmk-teknik.dk/160/advis"
		elementFormDefault="qualified">

	<include schemaLocation="RequestForWarrantIdentifier.xsd"/>
	<include schemaLocation="WarrantModificationIdentifiers.xsd"/>

	<complexType name="RequestForWarrantModificationIdentifiersType">
		<annotation>
			<documentation xml:lang="en-GB">Identifiers for a request-for-warrant modification</documentation>
			<documentation xml:lang="da-DK">Identifikatorer for en ændring af en anmodning om et udleveringsgrundlag</documentation>
		</annotation>
		<sequence>
			<element name="Identifier" type="mc160:RequestForWarrantIdentifierType"/>
			<element name="Warrant" type="mc160:WarrantModificationIdentifiersType" minOccurs="0">
				<annotation>
					<documentation xml:lang="en-GB">The warrant that fulfilled the request, if any</documentation>
					<documentation xml:lang="da-DK">Det udleveringsgrundlag der opfyldte anmodningen, hvis relevant</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
</schema>
